services:
  backend:
    build: ./backend_ai
    ports:
      - "8000:8000"
    volumes:
      - ./backend_ai:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: .  # ルートディレクトリでビルド
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend